#!/usr/bin/env bash
set -Eeuo pipefail
export PATH="/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin:${PATH:-}"

die() { printf 'Error: %s\n' "$*" >&2; exit 1; }
info() { printf '\n==> %s\n' "$*"; }

[[ ${EUID} -eq 0 ]] || die "Run this installer with sudo."

APP_USER=${SUDO_USER:-robert}
[[ ${APP_USER} != root ]] || die "Run with sudo from the account that owns the Plainwire repository."
APP_GROUP=$(id -gn "${APP_USER}")
REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
RELEASE="${REPO}/_build/default/rel/plainwire_relay/bin/plainwire_relay"
UPLOAD_DIR=/var/lib/plainwire/uploads
LOG_DIR=/var/log/plainwire
PG_SERVICE=postgresql-18

for command_name in openssl psql rebar3 elm sass rc-service rc-update supervise-daemon cloudflared curl; do
    command -v "${command_name}" >/dev/null || die "Required command is missing: ${command_name}"
done

printf 'Public Plainwire hostname (example: chat.example.com): '
read -r PUBLIC_HOST
PUBLIC_HOST=${PUBLIC_HOST#https://}
PUBLIC_HOST=${PUBLIC_HOST#http://}
PUBLIC_HOST=${PUBLIC_HOST%/}
[[ ${PUBLIC_HOST} =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]] || die "That is not a valid hostname."
[[ ${PUBLIC_HOST} != *.trycloudflare.com ]] \
    || die "trycloudflare.com is a temporary Quick Tunnel address and changes after restart. Use a hostname assigned to a named Cloudflare Tunnel for 24/7 hosting."

printf 'Paste the Cloudflare Tunnel token (input is hidden): '
read -rs TUNNEL_TOKEN
printf '\n'
[[ ${#TUNNEL_TOKEN} -ge 40 ]] || die "The tunnel token is missing or unexpectedly short."

DB_PASS=$(openssl rand -hex 32)
ENC_KEY=$(openssl rand -base64 32 | tr -d '\n')
MEDIA_KEY=$(openssl rand -base64 32 | tr -d '\n')

run_as_app() {
    su -s /bin/bash "${APP_USER}" -c "export PATH=/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin; $*"
}

info "Building optimized Elm, SCSS, Erlang, tests, and the release"
run_as_app "cd '${REPO}/priv/static/elm' && elm make src/Main.elm --output=../app.js --optimize"
run_as_app "cd '${REPO}' && sass priv/static/style.scss priv/static/app.css --no-source-map"
run_as_app "cd '${REPO}' && rebar3 compile && rebar3 eunit && rebar3 release"
[[ -x ${RELEASE} ]] || die "Release executable was not created."

info "Securing PostgreSQL account"
rc-service "${PG_SERVICE}" status >/dev/null 2>&1 || rc-service "${PG_SERVICE}" start
runuser -u postgres -- psql -v ON_ERROR_STOP=1 -d postgres \
    -c "ALTER ROLE plainwire WITH LOGIN PASSWORD '${DB_PASS}'" >/dev/null
runuser -u postgres -- psql -v ON_ERROR_STOP=1 -d postgres \
    -tAc "SELECT 1 FROM pg_database WHERE datname='plainwire'" | grep -qx 1 \
    || die "The PostgreSQL database named plainwire does not exist."

info "Installing protected configuration and storage directories"
install -d -o "${APP_USER}" -g "${APP_GROUP}" -m 0750 "${UPLOAD_DIR}" "${LOG_DIR}"
install -d -o root -g "${APP_GROUP}" -m 0750 /etc/cloudflared
umask 0077
printf '%s\n' "${TUNNEL_TOKEN}" > /etc/cloudflared/plainwire.token
chown root:"${APP_GROUP}" /etc/cloudflared/plainwire.token
chmod 0640 /etc/cloudflared/plainwire.token

cat > /etc/conf.d/plainwire <<EOF
# Generated by Plainwire's OpenRC installer. Keep this file secret.
export PLAINWIRE_ENV=production
export PORT=8080
export PLAINWIRE_PUBLIC_URL=https://${PUBLIC_HOST}
export PLAINWIRE_ALLOWED_ORIGINS=https://${PUBLIC_HOST}
export PLAINWIRE_TRUST_PROXY=true
export COOKIE_SECURE=true
export PLAINWIRE_ENC_KEY='${ENC_KEY}'
export PLAINWIRE_MEDIA_SIGNING_KEY='${MEDIA_KEY}'
export PLAINWIRE_DB_HOST=127.0.0.1
export PLAINWIRE_DB_PORT=5432
export PLAINWIRE_DB_USER=plainwire
export PLAINWIRE_DB_PASS='${DB_PASS}'
export PLAINWIRE_DB_NAME=plainwire
export PLAINWIRE_DB_SSL=false
export PLAINWIRE_ALLOW_INSECURE_DB=true
export PLAINWIRE_DB_POOL_SIZE=10
export PLAINWIRE_UPLOAD_DIR=${UPLOAD_DIR}
export PLAINWIRE_UPLOAD_MAX_BYTES=10485760
export PLAINWIRE_UPLOAD_QUOTA_BYTES=268435456
export PLAINWIRE_UPLOAD_RETENTION_DAYS=30
export PLAINWIRE_UPLOAD_CONCURRENCY=8
export PLAINWIRE_UPLOAD_USER_CONCURRENCY=2
export PLAINWIRE_MEDIA_ALLOWED_HOSTS=media.tenor.com,i.giphy.com,media.giphy.com
export PLAINWIRE_ALLOW_ARBITRARY_MEDIA=false
export PLAINWIRE_MEDIA_FETCH_CONCURRENCY=8
export PLAINWIRE_REQUIRE_TURN=false
EOF
chown root:"${APP_GROUP}" /etc/conf.d/plainwire
chmod 0640 /etc/conf.d/plainwire

cat > /etc/init.d/plainwire <<EOF
#!/sbin/openrc-run
name="Plainwire"
description="Plainwire chat server"
supervisor="supervise-daemon"
command="${RELEASE}"
command_args="foreground"
command_user="${APP_USER}:${APP_GROUP}"
directory="${REPO}"
respawn_delay=5
respawn_max=0
output_log="${LOG_DIR}/plainwire.log"
error_log="${LOG_DIR}/plainwire-error.log"
depend() {
    need net ${PG_SERVICE}
    after firewall
}
EOF
chmod 0755 /etc/init.d/plainwire

cat > /etc/init.d/cloudflared-plainwire <<EOF
#!/sbin/openrc-run
name="Cloudflare Tunnel for Plainwire"
description="Persistent outbound Cloudflare Tunnel"
supervisor="supervise-daemon"
command="/usr/bin/cloudflared"
command_args="tunnel --no-autoupdate run --token-file /etc/cloudflared/plainwire.token"
command_user="${APP_USER}:${APP_GROUP}"
respawn_delay=5
respawn_max=0
output_log="${LOG_DIR}/cloudflared.log"
error_log="${LOG_DIR}/cloudflared-error.log"
depend() {
    need net
    after plainwire
}
EOF
chmod 0755 /etc/init.d/cloudflared-plainwire

info "Enabling and starting services"
rc-update add "${PG_SERVICE}" default >/dev/null 2>&1 || true
rc-update add plainwire default >/dev/null 2>&1 || true
rc-update add cloudflared-plainwire default >/dev/null 2>&1 || true
if rc-service plainwire status >/dev/null 2>&1; then
    rc-service plainwire restart
else
    rc-service plainwire start
fi

for _ in $(seq 1 30); do
    if curl -fsS http://127.0.0.1:8080/ >/dev/null; then break; fi
    sleep 1
done
curl -fsS http://127.0.0.1:8080/ >/dev/null \
    || die "Plainwire did not answer on port 8080. Check ${LOG_DIR}/plainwire-error.log"

if rc-service cloudflared-plainwire status >/dev/null 2>&1; then
    rc-service cloudflared-plainwire restart
else
    rc-service cloudflared-plainwire start
fi

cat <<EOF

Plainwire is installed and running.

Local service:  http://127.0.0.1:8080
Public service: https://${PUBLIC_HOST}

In the Cloudflare dashboard, the tunnel's Published application must point
${PUBLIC_HOST} to http://127.0.0.1:8080. The tunnel token cannot change that
dashboard route by itself.

Useful commands:
  sudo rc-service plainwire status
  sudo rc-service cloudflared-plainwire status
  sudo tail -f ${LOG_DIR}/plainwire.log
  sudo tail -f ${LOG_DIR}/plainwire-error.log

The generated secrets are stored only in /etc/conf.d/plainwire.
Do not post or commit that file.
EOF
