-module(pw_scylla_statements).
-export([all/0]).

all() ->
    [{pw_msg_insert,
      <<"INSERT INTO messages_by_scope_bucket (scope,scope_id,bucket_start,message_id,user_id,body,reply_to_id,created_at,edited_at,deleted_at,kind,forwarded_from_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) USING TIMESTAMP ?">>},
     {pw_msg_locator_insert,
      <<"INSERT INTO message_locator_by_id (message_id,scope,scope_id,bucket_start,created_at) VALUES (?,?,?,?,?)">>},
     {pw_msg_locator_get,
      <<"SELECT scope,scope_id,bucket_start,created_at FROM message_locator_by_id WHERE message_id=?">>},
     {pw_msg_bucket_touch,
      <<"INSERT INTO message_buckets_by_scope (scope,scope_id,bucket_start) VALUES (?,?,?)">>},
     {pw_msg_buckets_recent,
      <<"SELECT bucket_start FROM message_buckets_by_scope WHERE scope=? AND scope_id=? ORDER BY bucket_start DESC LIMIT ?">>},
     {pw_msg_buckets_before,
      <<"SELECT bucket_start FROM message_buckets_by_scope WHERE scope=? AND scope_id=? AND bucket_start<=? ORDER BY bucket_start DESC LIMIT ?">>},
     {pw_msg_buckets_after,
      <<"SELECT bucket_start FROM message_buckets_by_scope WHERE scope=? AND scope_id=? AND bucket_start>=? ORDER BY bucket_start ASC LIMIT ?">>},
     {pw_msg_get,
      <<"SELECT message_id,user_id,body,reply_to_id,created_at,edited_at,deleted_at,kind,forwarded_from_id FROM messages_by_scope_bucket WHERE scope=? AND scope_id=? AND bucket_start=? AND message_id=?">>},
     {pw_msg_recent,
      <<"SELECT message_id,user_id,body,reply_to_id,created_at,edited_at,deleted_at,kind,forwarded_from_id FROM messages_by_scope_bucket WHERE scope=? AND scope_id=? AND bucket_start=? ORDER BY message_id DESC LIMIT ?">>},
     {pw_msg_before,
      <<"SELECT message_id,user_id,body,reply_to_id,created_at,edited_at,deleted_at,kind,forwarded_from_id FROM messages_by_scope_bucket WHERE scope=? AND scope_id=? AND bucket_start=? AND message_id<? ORDER BY message_id DESC LIMIT ?">>},
     {pw_msg_after,
      <<"SELECT message_id,user_id,body,reply_to_id,created_at,edited_at,deleted_at,kind,forwarded_from_id FROM messages_by_scope_bucket WHERE scope=? AND scope_id=? AND bucket_start=? AND message_id>? ORDER BY message_id ASC LIMIT ?">>},
     {pw_msg_edit,
      <<"UPDATE messages_by_scope_bucket USING TIMESTAMP ? SET body=?,edited_at=? WHERE scope=? AND scope_id=? AND bucket_start=? AND message_id=?">>},
     {pw_msg_delete,
      <<"UPDATE messages_by_scope_bucket USING TIMESTAMP ? SET body='',deleted_at=? WHERE scope=? AND scope_id=? AND bucket_start=? AND message_id=?">>},
     {pw_msg_hard_delete,
      <<"DELETE FROM messages_by_scope_bucket USING TIMESTAMP ? WHERE scope=? AND scope_id=? AND bucket_start=? AND message_id=?">>},
     {pw_msg_locator_delete,
      <<"DELETE FROM message_locator_by_id WHERE message_id=?">>},
     {pw_write_intent_bucket_touch,
      <<"INSERT INTO message_write_intent_buckets (directory,bucket_start) VALUES (?,?)">>},
     {pw_write_intent_buckets_recent,
      <<"SELECT bucket_start FROM message_write_intent_buckets WHERE directory=? ORDER BY bucket_start DESC LIMIT ?">>},
     {pw_write_intent_insert,
      <<"INSERT INTO message_write_intents_by_bucket (bucket_start,message_id,scope,scope_id,message_bucket,marked_at) VALUES (?,?,?,?,?,?)">>},
     {pw_write_intent_delete,
      <<"DELETE FROM message_write_intents_by_bucket WHERE bucket_start=? AND message_id=?">>},
     {pw_write_intents_first,
      <<"SELECT message_id,scope,scope_id,message_bucket,marked_at FROM message_write_intents_by_bucket WHERE bucket_start=? ORDER BY message_id ASC LIMIT ?">>},
     {pw_write_intents_after,
      <<"SELECT message_id,scope,scope_id,message_bucket,marked_at FROM message_write_intents_by_bucket WHERE bucket_start=? AND message_id>? ORDER BY message_id ASC LIMIT ?">>},
     {pw_event_bucket_touch,
      <<"INSERT INTO event_buckets_by_scope (scope,scope_id,bucket_start) VALUES (?,?,?)">>},
     {pw_event_buckets_recent,
      <<"SELECT bucket_start FROM event_buckets_by_scope WHERE scope=? AND scope_id=? ORDER BY bucket_start DESC LIMIT ?">>},
     {pw_event_buckets_before,
      <<"SELECT bucket_start FROM event_buckets_by_scope WHERE scope=? AND scope_id=? AND bucket_start<=? ORDER BY bucket_start DESC LIMIT ?">>},
     {pw_event_insert,
      <<"INSERT INTO message_events_by_scope_bucket (scope,scope_id,bucket_start,event_id,event_type,actor_id,entity_id,ts,payload) VALUES (?,?,?,?,?,?,?,?,?) USING TTL ?">>},
     {pw_event_range,
      <<"SELECT event_id,event_type,actor_id,entity_id,ts,payload FROM message_events_by_scope_bucket WHERE scope=? AND scope_id=? AND bucket_start=? AND event_id<? ORDER BY event_id DESC LIMIT ?">>},
     {pw_audit_bucket_touch,
      <<"INSERT INTO audit_buckets_by_server (server_id,bucket_start) VALUES (?,?)">>},
     {pw_audit_buckets_recent,
      <<"SELECT bucket_start FROM audit_buckets_by_server WHERE server_id=? ORDER BY bucket_start DESC LIMIT ?">>},
     {pw_audit_buckets_before,
      <<"SELECT bucket_start FROM audit_buckets_by_server WHERE server_id=? AND bucket_start<=? ORDER BY bucket_start DESC LIMIT ?">>},
     {pw_audit_insert,
      <<"INSERT INTO audit_events_by_server_bucket (server_id,bucket_start,event_id,actor_id,event_type,entity_id,ts,payload) VALUES (?,?,?,?,?,?,?,?) USING TTL ?">>},
     {pw_delivery_bucket_touch,
      <<"INSERT INTO delivery_buckets_by_server (server_id,bucket_start) VALUES (?,?)">>},
     {pw_delivery_buckets_recent,
      <<"SELECT bucket_start FROM delivery_buckets_by_server WHERE server_id=? ORDER BY bucket_start DESC LIMIT ?">>},
     {pw_delivery_buckets_before,
      <<"SELECT bucket_start FROM delivery_buckets_by_server WHERE server_id=? AND bucket_start<=? ORDER BY bucket_start DESC LIMIT ?">>},
     {pw_delivery_insert,
      <<"INSERT INTO delivery_events_by_server_bucket (server_id,bucket_start,event_id,target_type,target_id,status,http_status,attempt,latency_ms,ts,error_code) VALUES (?,?,?,?,?,?,?,?,?,?,?) USING TTL ?">>},
     {pw_audit_range,
      <<"SELECT event_id,actor_id,event_type,entity_id,ts,payload FROM audit_events_by_server_bucket WHERE server_id=? AND bucket_start=? AND event_id<? ORDER BY event_id DESC LIMIT ?">>},
     {pw_delivery_range,
      <<"SELECT event_id,target_type,target_id,status,http_status,attempt,latency_ms,ts,error_code FROM delivery_events_by_server_bucket WHERE server_id=? AND bucket_start=? AND event_id<? ORDER BY event_id DESC LIMIT ?">>}].
